import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/providers";
import { Toaster } from "react-hot-toast";
import { SessionExpiredModal } from "./components/ui/SessionExpiredModal";

const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: "Somo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-sans bg-white`}>
        <Toaster position="top-right"/>
        <Providers>
          {children}
          <SessionExpiredModal/>
        </Providers>
      </body>
    </html>
  );
}
